language: node_js

sudo: false

node_js:
  - "6"

after_script:
  - NODE_ENV=test istanbul cover ./node_modules/mocha/bin/_mocha --report lcovonly -- -R spec && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage

cache:
  directories:
    - node_modules
